# Generated by Django 5.2.8 on 2025-11-16 20:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=255, verbose_name='rua')),
                ('city', models.CharField(max_length=100, verbose_name='cidade')),
                ('state', models.CharField(max_length=100, verbose_name='estado')),
                ('zip_code', models.CharField(max_length=20, verbose_name='CEP')),
                ('country', models.CharField(default='Brasil', max_length=100, verbose_name='país')),
                ('complement', models.CharField(blank=True, max_length=255, verbose_name='complemento')),
                ('number', models.CharField(blank=True, max_length=20, verbose_name='número')),
                ('is_default', models.BooleanField(default=False, verbose_name='endereço padrão')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_addresses', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'endereço de entrega',
                'verbose_name_plural': 'endereços de entrega',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
