# Generated by Django 5.2.8 on 2025-11-16 20:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('PIX', 'PIX'), ('CREDIT_CARD', 'Cartão de Crédito'), ('DEBIT_CARD', 'Cartão de Débito'), ('BOLETO', 'Boleto')], max_length=20, verbose_name='método de pagamento')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PAID', 'Pago'), ('FAILED', 'Falhou'), ('REFUNDED', 'Reembolsado')], default='PENDING', max_length=20, verbose_name='status')),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID da transação')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='pago em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order', verbose_name='pedido')),
            ],
            options={
                'verbose_name': 'pagamento',
                'verbose_name_plural': 'pagamentos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', 'status'], name='payment_pay_order_i_b37863_idx'), models.Index(fields=['status', 'created_at'], name='payment_pay_status_19fbf4_idx'), models.Index(fields=['transaction_id'], name='payment_pay_transac_f578fa_idx')],
            },
        ),
    ]
