# Generated by Django 5.2.8 on 2025-11-16 20:16

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('subject', models.CharField(max_length=255, verbose_name='assunto')),
                ('message', models.TextField(verbose_name='mensagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('is_read', models.BooleanField(default=False, verbose_name='lido')),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='respondido em')),
                ('notes', models.TextField(blank=True, help_text='Notas internas sobre o atendimento', verbose_name='observações')),
            ],
            options={
                'verbose_name': 'mensagem de contato',
                'verbose_name_plural': 'mensagens de contato',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'created_at'], name='contact_con_email_02ea8f_idx'), models.Index(fields=['is_read', 'created_at'], name='contact_con_is_read_252076_idx')],
            },
        ),
    ]
