# Generated by Django 5.2.8 on 2025-11-16 20:11

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='slug')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='ícone')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('description', models.TextField(verbose_name='descrição')),
                ('brand', models.CharField(max_length=100, verbose_name='marca')),
                ('model', models.CharField(max_length=100, verbose_name='modelo')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='preço')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='preço com desconto')),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='estoque')),
                ('rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='avaliação média')),
                ('rating_count', models.IntegerField(default=0, verbose_name='quantidade de avaliações')),
                ('image_urls', models.JSONField(blank=True, default=list, verbose_name='URLs das imagens')),
                ('is_featured', models.BooleanField(default=False, verbose_name='destaque')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.category', verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'produto',
                'verbose_name_plural': 'produtos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100, verbose_name='chave')),
                ('value', models.CharField(max_length=255, verbose_name='valor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='catalog.product', verbose_name='produto')),
            ],
            options={
                'verbose_name': 'especificação técnica',
                'verbose_name_plural': 'especificações técnicas',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantidade reservada')),
                ('status', models.CharField(choices=[('RESERVED', 'Reservado'), ('CONVERTED', 'Convertido em venda'), ('EXPIRED', 'Expirado'), ('RELEASED', 'Liberado')], default='RESERVED', max_length=20, verbose_name='status')),
                ('expires_at', models.DateTimeField(verbose_name='expira em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('cart_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_reservation', to='cart.cartitem', verbose_name='item do carrinho')),
            ],
            options={
                'verbose_name': 'reserva de estoque',
                'verbose_name_plural': 'reservas de estoque',
                'ordering': ['-created_at'],
            },
        ),
    ]
