# Generated by Django 5.2.8 on 2025-11-16 20:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='subtítulo')),
                ('image_url', models.URLField(max_length=500, verbose_name='URL da imagem')),
                ('link', models.URLField(blank=True, help_text='Link para onde o banner redireciona', max_length=500, verbose_name='link')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('order', models.IntegerField(default=0, help_text='Banners com ordem menor aparecem primeiro', verbose_name='ordem de exibição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'banner',
                'verbose_name_plural': 'banners',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['active', 'order'], name='banner_bann_active_cc0fe1_idx')],
            },
        ),
    ]
